package com.adbkit.app.ui.strings

object EnStrings : AppStrings {
    override val langCode = "en"

    // Common
    override val appName = "ADB Kit"
    override val appSubtitle = "Professional ADB Assistant"
    override val menu = "Menu"
    override val settings = "Settings"
    override val refresh = "Refresh"
    override val cancel = "Cancel"
    override val confirm = "Confirm"
    override val close = "Close"
    override val ok = "OK"
    override val retry = "Retry"
    override val send = "Send"
    override val delete = "Delete"
    override val search = "Search"
    override val more = "More"
    override val copy = "Copy"
    override val execute = "Execute"
    override val connect = "Connect"
    override val disconnect = "Disconnect"
    override val disconnectConfirmTitle = "Disconnect Device"
    override val disconnectConfirmMessage = "Are you sure you want to disconnect? You will be returned to the home page."
    override val loading = "Loading..."
    override val noData = "No data"

    // Screen titles
    override val screenHome = "Connect"
    override val screenDeviceInfo = "Device Info"
    override val screenTools = "Tools"
    override val screenRemoteControl = "Remote Control"
    override val screenFileManager = "File Manager"
    override val screenAppManager = "App Manager"
    override val screenProcessManager = "Process Manager"
    override val screenTerminal = "Terminal"
    override val screenFastboot = "Fastboot"
    override val screenSettings = "Settings"

    // Home screen
    override val pair = "Pair"
    override val fastboot = "Fastboot"
    override val restartAdbService = "Restart ADB Service"
    override val disconnectAll = "Disconnect All"
    override val connectedDevices = { count: Int -> "$count device(s) connected" }
    override val wifiConnection = "WiFi"
    override val usbConnection = "USB"
    override val scan = "Scan"
    override val wirelessPair = "Wireless Pairing"
    override val wirelessPairDesc = "Android 11+ supports wireless debugging pairing. Get pairing info from Settings > Developer Options > Wireless Debugging."
    override val ipAddress = "IP Address"
    override val port = "Port"
    override val pairCode = "Pairing Code"
    override val restartingAdb = "Restarting ADB service..."
    override val adbRestarted = "ADB service restarted"
    override val restartFailed = { error: String -> "Restart failed: $error" }
    override val allDisconnected = "All devices disconnected"
    override val pairingSuccess = "Pairing successful"
    override val pairingFailed = "Pairing failed"
    override val fillAllFields = "Please fill in all fields"
    override val connectingTo = { addr: String -> "Connecting to $addr..." }
    override val connected = "Connected"
    override val connectFailed = { error: String -> "Connection failed: $error" }
    override val pleaseEnterIp = "Please enter IP address"

    // Device Info screen
    override val deviceInfo = "Device Info"
    override val copyAll = "Copy All"
    override val gettingDeviceInfo = "Getting device info..."
    override val basicInfo = "Basic Info"
    override val systemInfo = "System Info"
    override val hardwareInfo = "Hardware Info"
    override val batteryInfo = "Battery Info"
    override val networkInfo = "Network Info"
    override val otherInfo = "Other"
    override val moreInfo = "More Info"
    override val diModel = "Model"
    override val diBrand = "Brand"
    override val diDeviceName = "Device Name"
    override val diSerialNumber = "Serial Number"
    override val diHardware = "Hardware"
    override val diAndroidVersion = "Android Version"
    override val diSdkVersion = "SDK Version"
    override val diBuildId = "Build ID"
    override val diSecurityPatch = "Security Patch"
    override val diBasebandVersion = "Baseband Version"
    override val diKernelVersion = "Kernel Version"
    override val diCpuArch = "CPU Architecture"
    override val diScreenResolution = "Screen Resolution"
    override val diScreenDensity = "Screen Density"
    override val diTotalMemory = "Total Memory"
    override val diAvailableMemory = "Available Memory"
    override val diTotalStorage = "Total Storage"
    override val diAvailableStorage = "Available Storage"
    override val diBatteryLevel = "Battery Level"
    override val diBatteryStatus = "Battery Status"
    override val diBatteryTemperature = "Battery Temperature"
    override val diIpAddress = "IP Address"
    override val diWifiMac = "WiFi MAC"
    override val diUptime = "Uptime"

    // Tools screen
    override val tools = "Tools"
    override val toolScreenshot = "Screenshot"
    override val toolScreenRecord = "Screen Record"
    override val toolInstallApk = "Install APK"
    override val toolRebootDevice = "Reboot"
    override val toolInputText = "Input Text"
    override val toolKeyEvent = "Key Event"
    override val toolBrightness = "Brightness"
    override val toolScreenTimeout = "Screen Timeout"
    override val toolWifiToggle = "WiFi Toggle"
    override val toolBluetoothToggle = "Bluetooth"
    override val toolAirplaneMode = "Airplane Mode"
    override val toolOpenUrl = "Open URL"
    override val toolLaunchApp = "Launch App"
    override val toolCurrentActivity = "Current Activity"
    override val toolLogcat = "Logcat"
    override val toolSystemProperties = "System Props"
    override val toolScreenDensity = "Screen Density"
    override val toolScreenResolution = "Resolution"
    override val toolNavBar = "Nav Bar"
    override val toolStatusBar = "Status Bar"
    override val toolDescScreenshot = "Capture device screen"
    override val toolDescScreenRecord = "Record device screen"
    override val toolDescInstallApk = "Install application"
    override val toolDescRebootDevice = "Reboot to different modes"
    override val toolDescInputText = "Input text to device"
    override val toolDescKeyEvent = "Simulate key presses"
    override val toolDescBrightness = "Adjust screen brightness"
    override val toolDescScreenTimeout = "Set screen auto-off time"
    override val toolDescWifiToggle = "Toggle WiFi"
    override val toolDescBluetoothToggle = "Toggle Bluetooth"
    override val toolDescAirplaneMode = "Toggle airplane mode"
    override val toolDescOpenUrl = "Open URL on device"
    override val toolDescLaunchApp = "Launch specified app"
    override val toolDescCurrentActivity = "View current Activity"
    override val toolDescLogcat = "View system logs"
    override val toolDescSystemProperties = "View/modify system properties"
    override val toolDescScreenDensity = "Modify screen density DPI"
    override val toolDescScreenResolution = "Modify screen resolution"
    override val toolDescNavBar = "Show/hide navigation bar"
    override val toolDescStatusBar = "Show/hide status bar"
    override val rebootDevice = "Reboot Device"
    override val normalReboot = "Normal Reboot"
    override val rebootToRecovery = "Reboot to Recovery"
    override val rebootToBootloader = "Reboot to Bootloader"
    override val rebootToFastboot = "Reboot to Fastboot"
    override val rebootToEdl = "Reboot to EDL (9008)"
    override val inputText = "Input Text"
    override val textContent = "Text Content"
    override val keyEvent = "Key Event"
    override val keyHome = "Home"
    override val keyBack = "Back"
    override val keyVolUp = "Vol+"
    override val keyVolDown = "Vol-"
    override val keyPower = "Power"
    override val keyMenu = "Menu"
    override val keyRecent = "Recent"
    override val keyMute = "Mute"
    override val keySleep = "Sleep"
    override val keyWake = "Wake"
    override val keyTab = "Tab"
    override val keyEnter = "Enter"
    override val keyBackspace = "Backspace"
    override val keyEsc = "Esc"
    override val keyScreenshot = "Screenshot"
    override val screenBrightness = "Screen Brightness"
    override val brightnessValue = { v: Int -> "Brightness: $v" }
    override val set = "Set"
    override val openUrl = "Open URL"
    override val launchApp = "Launch App"
    override val packageName = "Package Name"
    override val launch = "Launch"
    override val modifyDensity = "Modify Screen Density"
    override val commonDpi = "Common DPI: 120(ldpi), 160(mdpi), 240(hdpi), 320(xhdpi), 480(xxhdpi), 640(xxxhdpi)"
    override val dpiValue = "DPI Value"
    override val resetDefault = "Reset Default"
    override val modifyResolution = "Modify Resolution"
    override val resolutionFormat = "Format: WxH (e.g. 1080x1920)"
    override val resolution = "Resolution"
    override val noLog = "No logs"
    override val clear = "Clear"

    // App Manager
    override val appManager = "App Manager"
    override val userApps = { count: Int -> "User Apps ($count)" }
    override val systemApps = { count: Int -> "System Apps ($count)" }
    override val searchPackage = "Search packages..."
    override val loadingAppList = "Loading app list..."
    override val appLaunch = "Launch"
    override val appForceStop = "Force Stop"
    override val appClearData = "Clear Data"
    override val appUninstall = "Uninstall"
    override val appFreeze = "Freeze/Disable"
    override val appEnable = "Enable"
    override val appBackupApk = "Backup APK"
    override val appDetails = "Details"
    override val action = "Actions"
    override val adVersionName = "Version"
    override val adVersionCode = "Version Code"
    override val adInstallTime = "Install Time"
    override val adUpdateTime = "Update Time"
    override val adApkPath = "APK Path"
    override val adDataDir = "Data Dir"
    override val adTargetSdk = "Target SDK"
    override val adMinSdk = "Min SDK"

    // File Manager
    override val fileManager = "File Manager"
    override val newFolder = "New Folder"
    override val homeDir = "Home"
    override val parentDir = "Parent Directory"
    override val sdCard = "SD Card"
    override val download = "Download"
    override val album = "DCIM"
    override val data = "Data"
    override val rootDir = "Root"
    override val emptyDir = "Empty directory"
    override val folderName = "Folder Name"
    override val create = "Create"
    override val downloadToLocal = "Download to local"

    // Process Manager
    override val processManager = "Process Manager"
    override val searchProcess = "Search processes..."
    override val totalProcesses = { count: Int -> "$count processes" }
    override val pid = "PID"
    override val memory = "Memory"
    override val processName = "Process"
    override val killProcess = "Kill Process"

    // Terminal
    override val terminal = "Terminal"
    override val clearScreen = "Clear"
    override val switchMode = "Switch Mode"
    override val adbShellMode = "ADB Shell Mode"
    override val adbCommandMode = "ADB Command Mode"
    override val notConnected = "Not connected"
    override val enterCommand = "Enter command..."
    override val history = "History"
    override val switchedToShellMode = "--- Switched to ADB Shell Mode ---"
    override val switchedToCommandMode = "--- Switched to ADB Command Mode ---"
    override val cleared = "--- Cleared ---"
    override val commandSuccess = "(Command executed successfully, no output)"
    override val commandFailed = "(Command execution failed)"

    // Fastboot
    override val fastbootDeviceConnected = "Fastboot device connected"
    override val fastbootInsertDevice = "Please insert device"
    override val flashImage = "Flash Image"
    override val imageFilePath = "Image file path"
    override val selectFile = "Select File"
    override val partition = "Partition"
    override val flash = "Flash"
    override val quickActions = "Quick Actions"
    override val rebootSystem = "Reboot"
    override val rebootBl = "Reboot BL"
    override val rebootRecovery = "Recovery"
    override val rebootFastbootd = "Fastbootd"
    override val unlockBl = "Unlock BL"
    override val lockBl = "Lock BL"
    override val erasePartition = "Erase Partition"
    override val deviceVariables = "Device Variables"
    override val customCommand = "Custom Command"
    override val commandOutput = "Command Output"
    override val detectDevice = "Detect Device"

    // Remote Control
    override val remoteControl = "Remote Control"
    override val fullscreen = "Fullscreen"
    override val gettingScreen = "Getting screen..."
    override val longPressToggleControls = "Long press to toggle controls"
    override val fpsOverlay = { fps: Int -> "$fps fps | Double tap to exit fullscreen" }
    override val refreshRate = "Refresh Rate"
    override val refreshRateLow = "Low (2fps)"
    override val refreshRateMid = "Medium (5fps)"
    override val refreshRateHigh = "High (10fps)"
    override val refreshRateUltra = "Ultra (20fps)"
    override val maxFps = "Max FPS"
    override val aspectRatio = "Aspect Ratio"
    override val keepOriginal = "Keep Original"
    override val adaptive = "Adaptive"
    override val navBarPosition = "Nav Bar Position"
    override val floating = "Floating"
    override val bottom = "Bottom"
    override val hidden = "Hidden"
    override val fullscreenDisplay = "Fullscreen Display"
    override val screenOffControl = "Screen Off Control"
    override val audioTransmission = "Audio Transmission"
    override val viewOnlyMode = "View Only Mode"
    override val usageGuide = "Usage Guide"
    override val usageTip1 = "• Tap on screen to operate remote device"
    override val usageTip2 = "• Swipe to simulate swipe actions"
    override val usageTip3 = "• Long press to toggle control bar"
    override val usageTip4 = "• Bottom bar provides Back/Home/Recent shortcuts"
    override val usageTip5 = "• Higher refresh rate = smoother but more resource usage"
    override val btnBack = "Back"
    override val btnHome = "Home"
    override val btnRecent = "Recent"

    // Settings
    override val adbConfig = "ADB Configuration"
    override val adbPath = "ADB Path"
    override val adbPathHint = "Default \"adb\", or specify full path like /data/local/tmp/adb (requires root)"
    override val detect = "Detect"
    override val autoDetect = "Auto Detect"
    override val fastbootPath = "Fastboot Path"
    override val defaultPort = "Default Port"
    override val connectionSettings = "Connection Settings"
    override val autoConnectLastDevice = "Auto connect last device"
    override val keepScreenOn = "Keep screen on"
    override val saveCommandHistory = "Save command history"
    override val safetySettings = "Safety Settings"
    override val confirmDangerous = "Confirm dangerous actions"
    override val confirmDangerousDesc = "Confirm before uninstall, reboot, erase, etc."
    override val appearanceSettings = "Appearance"
    override val darkMode = "Dark Mode"
    override val darkModeSystem = "System"
    override val darkModeLight = "Light"
    override val darkModeDark = "Dark"
    override val dynamicColor = "Dynamic Color (Material You)"
    override val dynamicColorDesc = "Android 12+ theme colors from wallpaper"
    override val languageSettings = "Language"
    override val language = "Interface Language"
    override val chinese = "中文"
    override val english = "English"
    override val about = "About"
    override val aboutAppName = "App Name"
    override val aboutVersion = "Version"
    override val aboutDeveloper = "Developer"
    override val aboutRepo = "Repository"
    override val adbStatusReady = "ADB Ready"
    override val adbStatusNotReady = "ADB Not Ready - Binary not found"
    override val adbDiagnostics = "Diagnostics"
    override val detecting = "Detecting..."
    override val autoDetecting = "Auto detecting..."
    override val adbAvailable = { info: String -> "✓ ADB available: $info" }
    override val adbUnavailable = { error: String -> "✗ ADB unavailable: $error" }
    override val adbFound = { path: String, info: String -> "✓ Found: $path\n$info" }
    override val adbNotFound = "✗ No ADB binary found"

    // History & Scan
    override val noHistory = "No history"
    override val scanningLan = "Scanning LAN..."
    override val scanResult = { count: Int -> "Found $count device(s)" }
    override val noDevicesFound = "No devices found"
    override val scanLan = "Scan LAN"

    // Device click target
    override val deviceClickTarget = "Device click target"
    override val deviceClickTargetDesc = "Target page when clicking device in list"

    // Sidebar device info
    override val currentDevice = "Current Device"
    override val noDeviceConnected = "No device connected"

    // File management
    override val upload = "Upload"
    override val uploadFile = "Upload File"
    override val downloading = "Downloading..."
    override val uploading = "Uploading..."
    override val downloadSuccess = "Download successful"
    override val uploadSuccess = "Upload successful"
    override val downloadFailed = "Download failed"
    override val uploadFailed = "Upload failed"

    // App management
    override val installApk = "Install APK"
    override val selectApk = "Select APK File"
    override val installing = "Installing..."
    override val installSuccess = "Install successful"
    override val installFailed = "Install failed"

    // Process management
    override val memoryUsage = "Memory Usage"
    override val totalMemory = "Total Memory"
    override val usedMemory = "Used Memory"
    override val freeMemory = "Free Memory"
    override val processKilled = "Process killed"
    override val runningApps = "Running Apps"
    override val allProcesses = "All Processes"
    override val runningAppsCount = { count: Int -> "$count running app(s)" }

    // Remote control - bitrate
    override val bitrateControl = "Bitrate"

    // Storage info
    override val storageInfo = "Storage Info"
    override val internalStorage = "Internal Storage"
    override val storageUsed = "Used"
    override val storageFree = "Free"
    override val storageTotal = "Total"
}
