package com.adbkit.app.ui.strings

object ZhStrings : AppStrings {
    override val langCode = "zh"

    // Common
    override val appName = "ADB Kit"
    override val appSubtitle = "专业ADB助手"
    override val menu = "菜单"
    override val settings = "设置"
    override val refresh = "刷新"
    override val cancel = "取消"
    override val stop = "停止"
    override val confirm = "确认"
    override val close = "关闭"
    override val ok = "确定"
    override val retry = "重试"
    override val send = "发送"
    override val delete = "删除"
    override val search = "搜索"
    override val more = "更多"
    override val copy = "复制"
    override val share = "分享"
    override val shareJson = "分享 JSON"
    override val execute = "执行"
    override val connect = "连接"
    override val disconnect = "断开"
    override val disconnectConfirmTitle = "断开设备连接"
    override val disconnectConfirmMessage = "确定要断开当前设备的连接吗？断开后将返回首页。"
    override val loading = "加载中..."
    override val noData = "暂无数据"

    // Screen titles
    override val screenHome = "连接"
    override val screenDeviceInfo = "设备信息"
    override val screenTools = "实用工具"
    override val screenRemoteControl = "远程控制"
    override val screenFileManager = "文件管理"
    override val screenAppManager = "应用管理"
    override val screenProcessManager = "进程管理"
    override val screenTerminal = "运行命令"
    override val screenFastboot = "Fastboot"
    override val screenSettings = "设置"

    // Home screen
    override val pair = "配对"
    override val fastboot = "Fastboot"
    override val restartAdbService = "重启 ADB 服务"
    override val disconnectAll = "断开所有设备"
    override val connectedDevices = { count: Int -> "已连接${count}个设备" }
    override val wifiConnection = "WiFi连接"
    override val usbConnection = "USB连接"
    override val scan = "扫描"
    override val wirelessPair = "无线配对"
    override val wirelessPairDesc = "Android 11+ 支持无线调试配对。请在设备设置 > 开发者选项 > 无线调试中获取配对信息。"
    override val ipAddress = "IP地址"
    override val localIp = "本机IP"
    override val port = "端口"
    override val pairCode = "配对码"
    override val restartingAdb = "正在重启 ADB 服务..."
    override val adbRestarted = "ADB 服务已重启"
    override val restartFailed = { error: String -> "重启失败: $error" }
    override val allDisconnected = "已断开所有设备"
    override val pairingSuccess = "配对成功"
    override val pairingFailed = "配对失败"
    override val fillAllFields = "请填写完整信息"
    override val connectingTo = { addr: String -> "正在连接 $addr..." }
    override val connected = "连接成功"
    override val connectionRefused = "连接被拒绝。请确认目标设备已开启 USB/无线调试，并允许此主机调试。"
    override val connectionUnreachable = "设备不可达。请检查 IP 地址，并确认两台设备在同一网络。"
    override val connectionOffline = "设备处于离线状态。请尝试在目标设备上重启 ADB 或重新授权。"
    override val connectionAuthFailed = "ADB 认证失败。请重新配对、撤销 USB 调试授权或重新插拔 USB。"
    override val connectionInvalidIp = "IP 地址或主机名无效。"
    override val connectionFailed = "无法连接到设备。"
    override val connectFailed = { error: String -> "连接失败: $error" }
    override val pleaseEnterIp = "请输入IP地址"

    // Device Info screen
    override val deviceInfo = "设备信息"
    override val copyAll = "复制全部"
    override val gettingDeviceInfo = "正在获取设备信息..."
    override val basicInfo = "基本信息"
    override val systemInfo = "系统信息"
    override val hardwareInfo = "硬件信息"
    override val batteryInfo = "电池信息"
    override val networkInfo = "网络信息"
    override val otherInfo = "其他"
    override val moreInfo = "更多信息"
    override val deviceOverview = "设备概览"
    override val diModel = "型号"
    override val diBrand = "品牌"
    override val diDeviceName = "设备名"
    override val diSerialNumber = "序列号"
    override val diHardware = "硬件"
    override val diAndroidVersion = "Android版本"
    override val diSdkVersion = "SDK版本"
    override val diBuildId = "Build ID"
    override val diSecurityPatch = "安全补丁"
    override val diBasebandVersion = "基带版本"
    override val diKernelVersion = "内核版本"
    override val diCpuArch = "CPU架构"
    override val diScreenResolution = "屏幕分辨率"
    override val diScreenDensity = "屏幕密度"
    override val diTotalMemory = "总内存"
    override val diAvailableMemory = "可用内存"
    override val diTotalStorage = "存储总量"
    override val diAvailableStorage = "存储可用"
    override val diBatteryLevel = "电池电量"
    override val diBatteryStatus = "电池状态"
    override val diBatteryTemperature = "电池温度"
    override val diIpAddress = "IP地址"
    override val diWifiMac = "WiFi MAC"
    override val diUptime = "运行时间"

    // Tools screen
    override val tools = "实用工具"
    override val toolScreenshot = "截图"
    override val toolScreenRecord = "录屏"
    override val toolInstallApk = "安装APK"
    override val toolRebootDevice = "重启设备"
    override val toolInputText = "输入文本"
    override val toolKeyEvent = "按键模拟"
    override val toolBrightness = "屏幕亮度"
    override val toolScreenTimeout = "屏幕超时"
    override val toolWifiToggle = "WiFi开关"
    override val toolBluetoothToggle = "蓝牙开关"
    override val toolAirplaneMode = "飞行模式"
    override val toolOpenUrl = "打开链接"
    override val toolLaunchApp = "启动应用"
    override val toolCurrentActivity = "当前Activity"
    override val toolLogcat = "Logcat"
    override val toolSystemProperties = "系统属性"
    override val toolScreenDensity = "屏幕密度"
    override val toolScreenResolution = "屏幕分辨率"
    override val toolNavBar = "导航栏"
    override val toolStatusBar = "状态栏"
    override val toolDescScreenshot = "截取设备屏幕"
    override val toolDescScreenRecord = "录制设备屏幕"
    override val toolDescInstallApk = "安装应用程序"
    override val toolDescRebootDevice = "重启到不同模式"
    override val toolDescInputText = "向设备输入文字"
    override val toolDescKeyEvent = "模拟按键操作"
    override val toolDescBrightness = "调节屏幕亮度"
    override val toolDescScreenTimeout = "设置屏幕自动关闭时间"
    override val toolDescWifiToggle = "开关WiFi"
    override val toolDescBluetoothToggle = "开关蓝牙"
    override val toolDescAirplaneMode = "开关飞行模式"
    override val toolDescOpenUrl = "在设备上打开URL"
    override val toolDescLaunchApp = "启动指定应用"
    override val toolDescCurrentActivity = "查看当前Activity"
    override val toolDescLogcat = "查看系统日志"
    override val toolDescSystemProperties = "查看/修改系统属性"
    override val toolDescScreenDensity = "修改屏幕密度DPI"
    override val toolDescScreenResolution = "修改屏幕分辨率"
    override val toolDescNavBar = "显示/隐藏导航栏"
    override val toolDescStatusBar = "显示/隐藏状态栏"
    override val rebootDevice = "重启设备"
    override val normalReboot = "正常重启"
    override val rebootToRecovery = "重启到Recovery"
    override val rebootToBootloader = "重启到Bootloader"
    override val rebootToFastboot = "重启到Fastboot"
    override val rebootToEdl = "重启到EDL(9008)"
    override val inputText = "输入文本"
    override val textContent = "文本内容"
    override val keyEvent = "按键模拟"
    override val keyHome = "Home"
    override val keyBack = "Back"
    override val keyVolUp = "音量+"
    override val keyVolDown = "音量-"
    override val keyPower = "电源键"
    override val keyMenu = "菜单"
    override val keyRecent = "最近任务"
    override val keyMute = "静音"
    override val keySleep = "休眠"
    override val keyWake = "唤醒"
    override val keyTab = "Tab"
    override val keyEnter = "Enter"
    override val keyBackspace = "退格"
    override val keyEsc = "Esc"
    override val keyScreenshot = "截图"
    override val screenBrightness = "屏幕亮度"
    override val brightnessValue = { v: Int -> "亮度值: $v" }
    override val set = "设置"
    override val openUrl = "打开链接"
    override val launchApp = "启动应用"
    override val packageName = "包名"
    override val launch = "启动"
    override val modifyDensity = "修改屏幕密度"
    override val commonDpi = "常见DPI: 120(ldpi), 160(mdpi), 240(hdpi), 320(xhdpi), 480(xxhdpi), 640(xxxhdpi)"
    override val dpiValue = "DPI值"
    override val resetDefault = "恢复默认"
    override val modifyResolution = "修改屏幕分辨率"
    override val resolutionFormat = "格式: 宽x高 (例如: 1080x1920)"
    override val resolution = "分辨率"
    override val noLog = "无日志"
    override val clear = "清除"
    override val propName = "属性名"
    override val propValue = "属性值"

    // App Manager
    override val appManager = "应用管理"
    override val userApps = { count: Int -> "用户应用 ($count)" }
    override val systemApps = { count: Int -> "系统应用 ($count)" }
    override val searchPackage = "搜索包名..."
    override val loadingAppList = "正在加载应用列表..."
    override val appLaunch = "启动"
    override val appForceStop = "强制停止"
    override val appClearData = "清除数据"
    override val appUninstall = "卸载"
    override val appFreeze = "冻结/禁用"
    override val appEnable = "启用"
    override val appBackupApk = "备份APK"
    override val appDetails = "详情"
    override val action = "操作"
    override val adVersionName = "版本名"
    override val adVersionCode = "版本号"
    override val adInstallTime = "安装时间"
    override val adUpdateTime = "更新时间"
    override val adApkPath = "APK路径"
    override val adDataDir = "数据目录"
    override val adTargetSdk = "目标SDK"
    override val adMinSdk = "最低SDK"
    override val adInstaller = "安装来源"
    override val adSignatures = "签名信息"

    // File Manager
    override val fileManager = "文件管理"
    override val newFolder = "新建文件夹"
    override val homeDir = "主目录"
    override val parentDir = "上级目录"
    override val sdCard = "SD卡"
    override val download = "下载"
    override val album = "相册"
    override val data = "数据"
    override val rootDir = "根目录"
    override val emptyDir = "空目录"
    override val folderName = "文件夹名称"
    override val create = "创建"
    override val downloadToLocal = "下载到本地"
    override val preview = "预览"
    override val previewImageError = "无法解析图片"
    override val unsupportedPreview = "暂不支持该文件类型的预览"
    override val rootRequired = "需要 Root 权限"
    override val rootRequiredMessage = "当前目录可能需要 root 权限，请确保设备已 root 并在 ADB shell 中运行 su。"

    // Process Manager
    override val processManager = "进程管理"
    override val searchProcess = "搜索进程..."
    override val totalProcesses = { count: Int -> "共 $count 个进程" }
    override val pid = "PID"
    override val memory = "内存"
    override val processName = "进程名"
    override val cpu = "CPU"
    override val killProcess = "结束进程"
    override val details = "详情"
    override val detailsPid = "进程 ID"
    override val detailsPpid = "父进程 ID"
    override val detailsThreads = "线程数"
    override val detailsCpuTime = "CPU 时间"
    override val detailsResidentPages = "常驻页"
    override val detailsCommandLine = "命令行"

    // Terminal
    override val terminal = "运行命令"
    override val clearScreen = "清屏"
    override val switchMode = "切换模式"
    override val adbShellMode = "ADB Shell 模式"
    override val adbCommandMode = "ADB 命令模式"
    override val notConnected = "未连接"
    override val enterCommand = "输入命令..."
    override val history = "历史"
    override val clearHistory = "清空历史"
    override val favorites = "收藏"
    override val addFavorite = "加入收藏"
    override val removeFavorite = "取消收藏"
    override val switchedToShellMode = "--- 切换到 ADB Shell 模式 ---"
    override val switchedToCommandMode = "--- 切换到 ADB 命令模式 ---"
    override val cleared = "--- 已清屏 ---"
    override val commandSuccess = "(命令执行成功，无输出)"
    override val commandFailed = "(命令执行失败)"

    // Fastboot
    override val fastbootDeviceConnected = "Fastboot 设备已连接"
    override val fastbootInsertDevice = "请插入设备"
    override val fastbootNoDevice = "未发现 Fastboot 设备。请将目标设备连接至本机 USB 端口。"
    override val fastbootNoPermission = "Fastboot 需要 root 或 USB 设备访问权限。请尝试以 root（su）运行本应用，或在 Magisk/KernelSU 中授予 USB 设备访问权限。"
    override val flashImage = "刷入镜像"
    override val imageFilePath = "镜像文件路径"
    override val selectFile = "选择文件"
    override val partition = "分区"
    override val flash = "刷入"
    override val quickActions = "快捷操作"
    override val rebootSystem = "重启系统"
    override val rebootBl = "重启BL"
    override val rebootRecovery = "重启Recovery"
    override val rebootFastbootd = "重启Fastbootd"
    override val unlockBl = "解锁BL"
    override val lockBl = "锁定BL"
    override val erasePartition = "擦除分区"
    override val deviceVariables = "设备变量"
    override val customCommand = "自定义命令"
    override val commandOutput = "命令行输出"
    override val saveLog = "保存日志"
    override val runScript = "执行脚本"
    override val macros = "脚本宏"
    override val macroName = "宏名称"
    override val saveMacro = "保存宏"
    override val noMacros = "暂无保存的宏"
    override val verifyMd5 = "校验 MD5"
    override val md5Result = "MD5: %s"
    override val md5Mismatch = "MD5 不匹配！期望 %s，实际 %s"
    override val expectedMd5 = "期望 MD5"
    override val partitionBackup = "分区备份"
    override val selectPartition = "选择分区"
    override val backupPartition = "备份分区"
    override val backupDestination = "备份目标路径"
    override val restorePartition = "还原分区"
    override val restoreImagePath = "还原镜像路径"
    override val detectDevice = "检测设备"

    // Remote Control
    override val remoteControl = "远程控制"
    override val remoteControlConnectHint = "请先返回首页连接设备，再回到本页面开始投屏。"
    override val fullscreen = "全屏"
    override val gettingScreen = "正在获取画面..."
    override val fpsOverlay = { fps: Int -> "$fps fps" }
    override val keepAspectRatio = "保持宽高比"
    override val navBarStyle = "导航栏样式"
    override val floating = "悬浮"
    override val bottom = "底部"
    override val hidden = "隐藏"
    override val screenOffControl = "熄屏控制"
    override val audioTransmission = "音频传输"
    override val audioNote = "音频转发需要设备端支持，当前仅预留开关，后续版本实现。"
    override val viewOnlyMode = "仅观看模式"
    override val weakNetworkMode = "弱网模式"
    override val fpsLowWarning = "检测到帧率较低（%d fps），是否降低码率/分辨率以获得更流畅的控制？"
    override val applyWeakNetwork = "应用低画质"
    override val weakNetworkApplied = "已保存弱网预设，下次开始投屏时生效。"
    override val weakNetworkHint = "开启后，帧率持续偏低时会自动提示降低码率/分辨率。"
    override val pressBackAgainToExit = "再按一次返回键退出远程控制"
    override val btnBack = "返回"
    override val btnHome = "主页"
    override val btnRecent = "最近"
    override val btnMore = "更多"
    override val btnVolumeUp = "音量加"
    override val btnVolumeDown = "音量减"
    override val btnPower = "电源"
    override val btnExit = "退出"
    override val btnPaste = "粘贴"

    override val remoteControlNoDevice = "未连接设备"
    override val remoteControlConnecting = "正在连接..."
    override val remoteControlConnected = "远程控制已连接"
    override val remoteControlConnectionFailed = "连接失败："
    override val remoteControlStreamError = "投屏错误："
    override val remoteControlTextSent = "文本已发送"
    override val remoteControlTextSendFailed = "发送失败："
    override val remoteControlClipboardEmpty = "剪贴板为空"
    override val remoteControlServerMissing = "投屏服务文件缺失"
    override val remoteControlPushFailed = "推送投屏服务失败："
    override val screenOffCommandSent = "熄屏指令已发送"
    override val screenOnCommandSent = "亮屏指令已发送"
    override val screenOffFailed = "熄屏失败"
    override val screenOnFailed = "亮屏失败"
    override val disconnected = "已断开"

    // Common status/error messages
    override val loadFailed = "加载失败"
    override val failedToGetInfo = "获取信息失败"
    override val unableToReadProcessDetails = "无法读取进程详情"
    override val textSent = "文本已发送"
    override val inputFailed = { error: String -> "输入失败: $error" }
    override val keyEventFailed = { error: String -> "按键事件失败: $error" }
    override val brightnessSet = { value: Int -> "亮度已设置为 $value" }
    override val screenTimeoutSet = "屏幕超时已设置为 5 分钟"
    override val setFailed = { error: String -> "设置失败: $error" }
    override val on = "开启"
    override val off = "关闭"
    override val shown = "显示"
    override val settingsExported = "设置已导出"
    override val settingsImported = "设置已导入"
    override val settingsExportFailed = "导出失败"
    override val settingsImportFailed = "导入失败"
    override val outputSaved = { output: String -> "输出已保存: $output" }
    override val saveFailed = { error: String -> "保存失败: $error" }
    override val noFavoriteCommands = "没有收藏命令可运行"
    override val runningFavorites = { count: Int -> "--- 正在运行收藏脚本 ($count 条命令) ---" }
    override val scriptFinished = "--- 脚本执行完成 ---"
    override val macroEmpty = { name: String -> "宏 '$name' 没有命令" }
    override val runningMacro = { name: String, count: Int -> "--- 正在运行宏 '$name' ($count 条命令) ---" }
    override val macroFinished = "--- 宏执行完成 ---"
    override val outputCleared = "--- 已清空 ---"
    override val okNoOutput = "(完成，无输出)"
    override val failed = "(失败)"
    override val cancelled = "(已取消)"
    override val md5MismatchDetail = { expected: String, got: String -> "MD5 不匹配! 期望 $expected, 实际 $got" }
    override val md5Value = { value: String -> "MD5: $value" }
    override val md5VerifyFailed = { error: String -> "MD5 校验失败: $error" }
    override val logSaved = { output: String -> "日志已保存: $output" }
    override val saveLogFailed = { error: String -> "保存日志失败: $error" }
    override val partitionsFound = { count: Int -> "找到 $count 个分区" }
    override val noPartitionsFound = "未找到分区 (可能需要 root)"
    override val selectPartitionPrompt = "请选择或输入分区名称"
    override val selectPartitionAndImage = "请选择分区并输入设备端镜像路径以还原"
    override val partitionBackupComplete = { output: String -> "备份完成: $output" }
    override val partitionBackupFailed = { error: String -> "备份失败: $error" }
    override val partitionRestoreComplete = { output: String -> "还原完成: $output" }
    override val partitionRestoreFailed = { error: String -> "还原失败: $error" }
    override val errorPrefix = { error: String -> "错误: $error" }
    override val toggleState = { label: String, state: String -> "$label$state" }
    override val urlOpened = "链接已打开"
    override val openUrlFailed = { error: String -> "打开失败: $error" }
    override val currentActivityFailed = { error: String -> "获取当前窗口失败: $error" }
    override val logCleared = "日志已清空"
    override val settingProperty = { name: String -> "正在设置 $name..." }
    override val propertySet = { name: String -> "属性 $name 已设置" }
    override val densityChanged = "屏幕密度已更改"
    override val resolutionChanged = "屏幕分辨率已更改"
    override val changeFailed = { error: String -> "更改失败: $error" }
    override val operationFailed = { error: String -> "失败: $error" }
    override val killFailed = { error: String -> "结束进程失败: $error" }
    override val stoppingApp = { pkg: String -> "正在停止 $pkg..." }
    override val appStopped = { pkg: String -> "$pkg 已停止" }
    override val stopFailed = { error: String -> "停止失败: $error" }
    override val connecting = "连接中..."
    override val disconnectedFrom = { device: String -> "已断开 $device" }
    override val cannotGetLocalIp = "无法获取本机 IP，请检查 WiFi 连接"
    override val pairingInProgress = "配对中..."
    override val deleteFailed = { error: String -> "删除失败: $error" }
    override val renameFailed = { error: String -> "重命名失败: $error" }
    override val moveFailed = { error: String -> "移动失败: $error" }
    override val copyFailed = { error: String -> "复制失败: $error" }
    override val uploadFailedFmt = { error: String -> "上传失败: $error" }
    override val downloadFailedFmt = { error: String -> "下载失败: $error" }
    override val createFailed = { error: String -> "创建失败: $error" }
    override val batchDeleteFailed = { count: Int, error: String -> "批量删除失败 $count 项: $error" }
    override val deletedItems = { count: Int -> "已删除 $count 项" }
    override val downloadedFile = { file: String, size: String, path: String -> "已下载 $file ($size) 到 $path" }
    override val uploadedFile = { file: String, size: String -> "已上传 $file ($size)" }
    override val unsupportedFileType = "不支持的文件类型"
    override val noAppsToBackup = "没有可备份的应用"
    override val backingUpApp = { pkg: String -> "正在备份 $pkg..." }
    override val backingUpApps = { count: Int -> "正在备份 $count 个应用..." }
    override val backupComplete = { success: Int, failed: Int, dir: String -> "备份完成: $success 成功, $failed 失败. 保存到 $dir" }
    override val backedUpTo = { path: String -> "已备份到 $path" }
    override val backupFailed = { error: String -> "备份失败: $error" }
    override val appEnabled = { pkg: String -> "$pkg 已启用" }
    override val enableFailed = { error: String -> "启用失败: $error" }
    override val appDisabled = { pkg: String -> "$pkg 已禁用" }
    override val disableFailed = { error: String -> "禁用失败: $error" }
    override val appLaunched = { pkg: String -> "$pkg 已启动" }
    override val launchFailed = { error: String -> "启动失败: $error" }
    override val appUninstalled = { pkg: String -> "$pkg 已卸载" }
    override val uninstallFailed = { error: String -> "卸载失败: $error" }
    override val appDataCleared = { pkg: String -> "$pkg 数据已清除" }
    override val clearDataFailed = { error: String -> "清除数据失败: $error" }
    override val appForceStopped = { pkg: String -> "$pkg 已强制停止" }
    override val forceStopFailed = { error: String -> "强制停止失败: $error" }
    override val installFailedFmt = { error: String -> "安装失败: $error" }
    override val pushFailed = { error: String -> "推送失败: $error" }
    override val exportingAppList = "正在导出应用列表..."
    override val appListExported = { path: String -> "应用列表已导出到 $path" }
    override val exportFailed = { error: String -> "导出失败: $error" }
    override val downloadingFile = { file: String -> "正在下载 $file..." }
    override val uploadingFile = { file: String, size: String -> "正在上传 $file ($size)..." }
    override val previewFailed = { error: String -> "预览失败: $error" }
    override val installingFile = { file: String -> "正在安装 $file..." }
    override val installedFile = { file: String -> "$file 已安装" }
    override val takingScreenshot = "正在截图..."
    override val screenshotSaved = { path: String -> "截图已保存到 $path" }
    override val screenshotFailed = { error: String -> "截图失败: $error" }
    override val recording = "正在录屏..."
    override val recordingFile = { path: String -> "正在录屏... 文件: $path" }
    override val recordingSaved = { path: String -> "录屏已保存到 $path" }
    override val recordingStopped = "录屏已停止"
    override val recordFailed = { error: String -> "录屏失败: $error" }
    override val rebooting = "正在重启..."
    override val rebootCommandSent = "重启指令已发送"
    override val rebootFailed = { error: String -> "重启失败: $error" }
    override val pleaseSelectApk = "请通过文件管理器选择 APK"

    // Settings
    override val adbConfig = "ADB 配置"
    override val adbPath = "ADB 路径"
    override val adbPathHint = "默认 \"adb\"，可指定完整路径如 /data/local/tmp/adb（需root权限）"
    override val detect = "检测"
    override val autoDetect = "自动查找"
    override val fastbootPath = "Fastboot 路径"
    override val defaultPort = "默认端口"
    override val connectionSettings = "连接设置"
    override val autoConnectLastDevice = "自动连接上次设备"
    override val keepScreenOn = "保持屏幕常亮"
    override val saveCommandHistory = "保存命令历史"
    override val safetySettings = "安全设置"
    override val confirmDangerous = "危险操作确认"
    override val confirmDangerousDesc = "卸载、重启、擦除等操作前需要确认"
    override val appearanceSettings = "外观设置"
    override val darkMode = "深色模式"
    override val darkModeSystem = "跟随系统"
    override val darkModeLight = "浅色"
    override val darkModeDark = "深色"
    override val dynamicColor = "动态颜色 (Material You)"
    override val dynamicColorDesc = "Android 12+ 根据壁纸生成主题色"
    override val languageSettings = "语言设置"
    override val language = "界面语言"
    override val chinese = "中文"
    override val english = "English"
    override val languageSystem = "跟随系统"
    override val about = "关于"
    override val aboutAppName = "应用名称"
    override val aboutVersion = "版本"
    override val aboutDeveloper = "开发者"
    override val aboutRepo = "项目地址"
    override val exportSettings = "导出设置"
    override val importSettings = "导入设置"
    override val adbStatusReady = "ADB 已就绪"
    override val adbStatusNotReady = "ADB 未就绪 - 无法找到ADB可执行文件"
    override val adbDiagnostics = "诊断信息"
    override val detecting = "检测中..."
    override val autoDetecting = "自动检测中..."
    override val adbAvailable = { info: String -> "✓ ADB 可用: $info" }
    override val adbUnavailable = { error: String -> "✗ ADB 不可用: $error" }
    override val adbFound = { path: String, info: String -> "✓ 已找到: $path\n$info" }
    override val adbNotFound = "✗ 未找到可用的adb"

    // History & Scan
    override val recentConnections = "最近连接"
    override val noHistory = "暂无历史记录"
    override val scanningLan = "正在扫描局域网..."
    override val scanResult = { count: Int -> "发现 $count 个设备" }
    override val noDevicesFound = "未发现设备"
    override val scanLan = "扫描局域网"
    override val startPort = "起始端口"
    override val endPort = "结束端口"
    override val timeout = "超时 (ms)"
    override val startScan = "开始扫描"
    override val welcomeTitle = "欢迎使用 ADB Kit"
    override val welcomeDescription = "通过 USB 或 WiFi 连接到另一台 Android 设备，开始使用。"
    override val welcomeStep1 = "在目标设备上开启 USB 调试或无线调试"
    override val welcomeStep2 = "输入 IP 地址点击连接，或使用扫描局域网"
    override val welcomeStep3 = "如有存储权限提示，请授权以便管理本地文件"
    override val fastbootGuideTitle = "Fastboot 引导"
    override val fastbootGuideStep1 = "将设备重启至 Fastboot 模式（通常为音量下+电源键）"
    override val fastbootGuideStep2 = "若未检测到设备，请授予 root 或 USB 权限"
    override val fastbootGuideStep3 = "选择镜像、校验 MD5，然后刷入目标分区"
    override val remoteControlGuideTitle = "远程控制引导"
    override val remoteControlGuideStep1 = "先在首页连接目标设备"
    override val remoteControlGuideStep2 = "调整分辨率/码率；卡顿时可开启弱网模式"
    override val remoteControlGuideStep3 = "点击连接开始投屏并远程控制"
    override val crashLog = "崩溃日志"
    override val noCrashLogs = "暂无崩溃日志"
    override val shareCrashLog = "分享最新崩溃日志"
    override val clearCrashLogs = "清空崩溃日志"
    override val feedback = "发送反馈"
    override val help = "帮助"
    override val onboardingTitle = "欢迎使用 ADB Kit"
    override val onboardingStep1Title = "连接设备"
    override val onboardingStep1Body = "在目标设备上开启 USB 调试，通过 USB 连接；或使用无线调试，输入 IP:端口 即可连接。"
    override val onboardingStep2Title = "授予权限"
    override val onboardingStep2Body = "允许存储权限，以便 ADB Kit 拉取文件、安装 APK、保存日志和截图到本地。"
    override val onboardingStep3Title = "探索功能"
    override val onboardingStep3Body = "使用设备信息、文件管理、应用管理、进程管理、终端、远程控制与 Fastboot 等工具。"
    override val onboardingTip = "提示：你可以随时在设置 > 帮助中再次查看本引导。"
    override val onboardingFinish = "开始使用"
    override val helpContent = "## 如何开启 USB 调试\n• 在目标设备上进入「设置 > 关于手机」，连续点击「版本号」7 次开启开发者选项。\n• 进入「设置 > 系统 > 开发者选项」，开启「USB 调试」。\n• 使用 USB 线连接设备，并在弹窗中允许此主机调试。\n\n## 如何开启无线调试\n• 确保两台设备连接同一 Wi-Fi。\n• Android 11+：进入开发者选项 > 无线调试，使用 IP/端口/配对码完成配对。\n• 在 ADB Kit 中输入 IP:端口，点击连接。\n\n## 为什么需要存储权限\n• ADB Kit 需从目标设备下载文件到本地，并管理缓存/图片等。\n• 若未授予「所有文件访问权限」，pull/push 和 APK 安装可能失败。\n\n## 主要功能\n• 设备信息：查看完整设备参数，导出 JSON，查看电池/存储历史趋势折线图。\n• 文件管理：浏览、上传、下载、重命名、复制、移动、预览文件并显示进度。\n• 应用管理：用户/系统应用分类，批量备份 APK，导出应用列表，查看详情。\n• 进程管理：监控运行进程，按 CPU/内存/PID 排序，结束进程。\n• 命令终端：执行 ADB/Shell 命令，收藏命令，保存命令宏并一键运行，分享输出。\n• 远程控制：类 scrcpy 投屏，支持触控、键盘输入与弱网预设。\n• Fastboot：分区备份/还原、镜像 MD5 校验。\n• 实用工具：截图、录屏、亮度、重启、系统属性 setprop 等。\n\n## 常见连接错误\n• 连接被拒绝：请确认目标设备已开启 USB/无线调试并授权此主机。\n• 设备不可达：请检查 IP 地址，确认两台设备在同一网络。\n• 未授权：撤销「USB 调试授权」后重新插拔 USB 或重新配对。\n\n## 远程控制提示\n• 开始投屏前必须先连接设备。\n• 如果画面卡顿，可在设置中降低码率/分辨率。\n• 音频转发需要设备端支持，当前仅预留开关。\n\n## Fastboot 注意事项\n• Fastboot 通常需要 USB 线连接。\n• 在手机端运行 Fastboot 可能需要 root 或直接 USB 设备访问权限；请按需授权。\n• 刷入错误镜像可能导致设备变砖，请仔细核对分区和镜像文件。\n\n## 仍有问题？\n• 可在 设置 > 反馈 中发送崩溃日志或建议。\n• 访问项目仓库中的 docs/product-evaluation-and-roadmap.md 查看完整路线图。"

    // Device click target
    override val deviceClickTarget = "设备点击跳转"
    override val deviceClickTargetDesc = "点击设备列表时跳转的目标页面"

    // Sidebar device info
    override val currentDevice = "当前设备"
    override val noDeviceConnected = "未连接设备"

    // File management
    override val upload = "上传"
    override val uploadFile = "上传文件"
    override val downloading = "下载中..."
    override val uploading = "上传中..."
    override val downloadSuccess = "下载成功"
    override val uploadSuccess = "上传成功"
    override val downloadFailed = "下载失败"
    override val uploadFailed = "上传失败"
    override val rename = "重命名"
    override val move = "移动"
    override val newName = "新名称"
    override val targetPath = "目标路径"

    // App management
    override val installApk = "安装 APK"
    override val selectApk = "选择 APK 文件"
    override val installing = "安装中..."
    override val installSuccess = "安装成功"
    override val installFailed = "安装失败"
    override val exportAppList = "导出应用列表"
    override val activities = "活动"
    override val services = "服务"
    override val receivers = "接收器"
    override val providers = "内容提供"

    // Process management
    override val memoryUsage = "内存占用"
    override val totalMemory = "总内存"
    override val usedMemory = "已用内存"
    override val freeMemory = "可用内存"
    override val processKilled = "进程已结束"
    override val runningApps = "运行中应用"
    override val allProcesses = "全部进程"
    override val runningAppsCount = { count: Int -> "共 $count 个运行中应用" }

    // Remote control - bitrate
    override val bitrateControl = "码率控制"

    // Storage info
    override val storageInfo = "存储信息"
    override val internalStorage = "内部存储"
    override val storageUsed = "已用"
    override val storageFree = "可用"
    override val storageTotal = "总计"
}
